services:
  db:
    image: postgres:18.4
    container_name: team-expense-db

    ports:
      - "${DB_PORT}:5432"

    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"

    volumes:
      - team-expense-db-data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  team-expense-db-data: