CREATE TABLE expenses (
  id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  requester_id INTEGER NOT NULL,
  title VARCHAR(20) NOT NULL
    CHECK (char_length(btrim(title)) BETWEEN 2 AND 20),
  amount INTEGER NOT NULL
    CHECK (amount > 0),
  expense_at TIMESTAMPTZ NOT NULL,
  category VARCHAR(20) NOT NULL
    CHECK (category IN ('MEAL', 'TRANSPORT', 'SUPPLIES', 'OTHER')),
  memo VARCHAR(100),
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING'
    CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
  submitted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);